export const CASE_INTAKE = 'CASE_INTAKE';
export const CASE_INTAKE_TAB_CHANGE = 'CASE_INTAKE_TAB_CHANGE';
export const SUMMARY = 'SUMMARY';
export const CASE_INTAKE_ADD_GENERAL = 'CASE_INTAKE_ADD_GENERAL';
export const CASE_INTAKE_FRONT_PAGE = 'CASE_INTAKE_FRONT_PAGE';
